spring.application.name=outsourcing

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
jwt.secret.key=${JWT_SECRET_KEY}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto= update

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

KAKAO_API_KEY = ${KAKAO_API_KEY}
logging.level.com.example.outsourcing.domain.common.service.GeoCodingService = debug


aws.s3.bucket-name=outsourcing-image

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=20MB
aws.credentials.access-key=${AWS_ACCESS_KEY}
aws.credentials.secret-key=${AWS_SECRET_KEY}
aws.region=us-east-1

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.client-name=${REDIS_CLIENT_NAME}
spring.data.redis.password=${REDIS_PASSWORD}
spring.data.redis.port=${REDIS_PORT}
spring.data.redis.timeout=5000

